# -*- coding: utf-8 -*-
"""4c

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xNOpSt5UG9SgLVXVEuTN6w30HGoy-jaL
"""

import numpy as np
import pandas as pd

train_data = pd.read_csv("Concrete/train.csv",header=None)

X = train_data.iloc[:,:-1]
Y = train_data.iloc[:,-1]
X_train = np.column_stack(([1]*X.shape[0], X))
X = np.array(X_train)
Y = np.array(Y)

print("Optimal weight vector that is calculated with the analytical form is : ",np.dot(np.linalg.inv(np.dot(X.T,X)),np.dot(X.T,Y)))



X = train_data.iloc[:,:-1]
Y = train_data.iloc[:,-1]
X = np.array(X)
Y = np.array(Y)

print("Optimal weight vector that is calculated with the analytical form without bias feature is : ",np.dot(np.linalg.inv(np.dot(X.T,X)),np.dot(X.T,Y)))

